#! /bin/bash

THIS="$( readlink -f "${BASH_SOURCE[0]}" )"
DIR="$( dirname "$THIS" )"
JPLOOT_HOME="$( readlink -f "${DIR}/.." )"
JAVA_HOME="[[JAVA_HOME]]"

export JPLOOT_HOME

exec "$JAVA_HOME/bin/java" -cp [[CLASSPATH]] '[[MAINCLASS]]' "$@"
