#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
JAVA_HOME="$( readlink -f "${DIR}/.." )"

export JAVA_HOME

exec "$JAVA_HOME/bin/java" -cp [[CLASSPATH]] '[[MAINCLASS]]' "$@"